export enum Tool {
  PORTER = 'PORTER',
  PESTEL = 'PESTEL',
  OKR = 'OKR',
  MCKINSEY = 'MCKINSEY',
  FODA = 'FODA',
  BALANCED_SCORECARD = 'BALANCED_SCORECARD',
  ANSOFF = 'ANSOFF',
  QUESTIONNAIRE = 'QUESTIONNAIRE',
  HUB = 'HUB',
}
